/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ClockSymbol: typeof import('./../components/symbols/ClockSymbol.vue')['default']
    CubeSymbol: typeof import('./../components/symbols/CubeSymbol.vue')['default']
    DotsSymbol: typeof import('./../components/symbols/DotsSymbol.vue')['default']
    DrawnSymbol: typeof import('./../components/symbols/DrawnSymbol.vue')['default']
    Icon: typeof import('./../components/shared/Icon.vue')['default']
    MotionSymbol: typeof import('./../components/symbols/MotionSymbol.vue')['default']
    Navigation: typeof import('./../components/layouts/elements/Navigation.vue')['default']
    NoiseSymbol: typeof import('../components/symbols/MotionSymbol.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SquareSymbol: typeof import('./../components/symbols/SquareSymbol.vue')['default']
    SwipeOverlay: typeof import('./../components/layouts/elements/SwipeOverlay.vue')['default']
    Time: typeof import('./../components/layouts/Time.vue')['default']
    TimeSorted: typeof import('./../components/layouts/TimeSorted.vue')['default']
  }
}
