/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ClockSymbol: typeof import('./../components/ClockSymbol.vue')['default']
    CubeSymbol: typeof import('./../components/CubeSymbol.vue')['default']
    DotsSymbol: typeof import('./../components/DotsSymbol.vue')['default']
    DotSymbol: typeof import('../components/DotsSymbol.vue')['default']
    DrawnSymbol: typeof import('./../components/DrawnSymbol.vue')['default']
    Icon: typeof import('./../components/Icon.vue')['default']
    Navigation: typeof import('./../components/Navigation.vue')['default']
    NoiseSymbol: typeof import('./../components/NoiseSymbol.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SquareSymbol: typeof import('./../components/SquareSymbol.vue')['default']
    Time: typeof import('./../components/Time.vue')['default']
    'Time.1': typeof import('../components/TimeSorted.vue')['default']
    TimeSorted: typeof import('./../components/TimeSorted.vue')['default']
  }
}
